// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_invites.sql

package db

import (
	"context"
)

const createClubInvite = `-- name: CreateClubInvite :exec
INSERT INTO club_invites (id, club_id, inviter_id, invitee_id, status, created_at)
VALUES (?, ?, ?, ?, 'pending', ?)
`

type CreateClubInviteParams struct {
	ID        string
	ClubID    string
	InviterID string
	InviteeID string
	CreatedAt string
}

func (q *Queries) CreateClubInvite(ctx context.Context, arg CreateClubInviteParams) error {
	_, err := q.db.ExecContext(ctx, createClubInvite,
		arg.ID,
		arg.ClubID,
		arg.InviterID,
		arg.InviteeID,
		arg.CreatedAt,
	)
	return err
}

const getClubInvite = `-- name: GetClubInvite :one
SELECT
    ci.id,
    ci.club_id,
    c.name AS club_name,
    c.avatar_icon AS club_avatar_icon,
    c.avatar_color AS club_avatar_color,
    ci.inviter_id,
    iu.display_name AS inviter_display_name,
    ci.invitee_id,
    ci.status,
    ci.created_at
FROM club_invites ci
JOIN clubs c ON c.id = ci.club_id
JOIN users iu ON iu.id = ci.inviter_id
WHERE ci.id = ?
`

type GetClubInviteRow struct {
	ID                 string
	ClubID             string
	ClubName           string
	ClubAvatarIcon     string
	ClubAvatarColor    string
	InviterID          string
	InviterDisplayName string
	InviteeID          string
	Status             string
	CreatedAt          string
}

func (q *Queries) GetClubInvite(ctx context.Context, id string) (GetClubInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getClubInvite, id)
	var i GetClubInviteRow
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.ClubName,
		&i.ClubAvatarIcon,
		&i.ClubAvatarColor,
		&i.InviterID,
		&i.InviterDisplayName,
		&i.InviteeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getClubInviteByClubAndInvitee = `-- name: GetClubInviteByClubAndInvitee :one
SELECT id, status FROM club_invites WHERE club_id = ? AND invitee_id = ?
`

type GetClubInviteByClubAndInviteeParams struct {
	ClubID    string
	InviteeID string
}

type GetClubInviteByClubAndInviteeRow struct {
	ID     string
	Status string
}

func (q *Queries) GetClubInviteByClubAndInvitee(ctx context.Context, arg GetClubInviteByClubAndInviteeParams) (GetClubInviteByClubAndInviteeRow, error) {
	row := q.db.QueryRowContext(ctx, getClubInviteByClubAndInvitee, arg.ClubID, arg.InviteeID)
	var i GetClubInviteByClubAndInviteeRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getClubInvitesByInviteeID = `-- name: GetClubInvitesByInviteeID :many
SELECT
    ci.id,
    ci.club_id,
    c.name AS club_name,
    c.avatar_icon AS club_avatar_icon,
    c.avatar_color AS club_avatar_color,
    ci.inviter_id,
    iu.display_name AS inviter_display_name,
    ci.status,
    ci.created_at
FROM club_invites ci
JOIN clubs c ON c.id = ci.club_id
JOIN users iu ON iu.id = ci.inviter_id
WHERE ci.invitee_id = ? AND ci.status = 'pending'
ORDER BY ci.created_at DESC
`

type GetClubInvitesByInviteeIDRow struct {
	ID                 string
	ClubID             string
	ClubName           string
	ClubAvatarIcon     string
	ClubAvatarColor    string
	InviterID          string
	InviterDisplayName string
	Status             string
	CreatedAt          string
}

func (q *Queries) GetClubInvitesByInviteeID(ctx context.Context, inviteeID string) ([]GetClubInvitesByInviteeIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getClubInvitesByInviteeID, inviteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClubInvitesByInviteeIDRow{}
	for rows.Next() {
		var i GetClubInvitesByInviteeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.ClubName,
			&i.ClubAvatarIcon,
			&i.ClubAvatarColor,
			&i.InviterID,
			&i.InviterDisplayName,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetClubInvite = `-- name: ResetClubInvite :exec
UPDATE club_invites SET status = 'pending', inviter_id = ? WHERE id = ?
`

type ResetClubInviteParams struct {
	InviterID string
	ID        string
}

func (q *Queries) ResetClubInvite(ctx context.Context, arg ResetClubInviteParams) error {
	_, err := q.db.ExecContext(ctx, resetClubInvite, arg.InviterID, arg.ID)
	return err
}

const updateClubInviteStatus = `-- name: UpdateClubInviteStatus :exec
UPDATE club_invites SET status = ? WHERE id = ?
`

type UpdateClubInviteStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateClubInviteStatus(ctx context.Context, arg UpdateClubInviteStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateClubInviteStatus, arg.Status, arg.ID)
	return err
}
