// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clubs.sql

package db

import (
	"context"
	"database/sql"
)

const createClub = `-- name: CreateClub :exec
INSERT INTO clubs (id, name, description, avatar_icon, avatar_color, join_code, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateClubParams struct {
	ID          string
	Name        string
	Description string
	AvatarIcon  string
	AvatarColor string
	JoinCode    string
	CreatedBy   string
	CreatedAt   string
}

func (q *Queries) CreateClub(ctx context.Context, arg CreateClubParams) error {
	_, err := q.db.ExecContext(ctx, createClub,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.JoinCode,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteClub = `-- name: DeleteClub :exec
DELETE FROM clubs WHERE id = ?
`

func (q *Queries) DeleteClub(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClub, id)
	return err
}

const deleteClubMember = `-- name: DeleteClubMember :exec
DELETE FROM club_members WHERE club_id = ? AND user_id = ?
`

type DeleteClubMemberParams struct {
	ClubID string
	UserID string
}

func (q *Queries) DeleteClubMember(ctx context.Context, arg DeleteClubMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteClubMember, arg.ClubID, arg.UserID)
	return err
}

const getClub = `-- name: GetClub :one
SELECT id, name, description, avatar_icon, avatar_color, join_code, created_by, created_at
FROM clubs WHERE id = ?
`

func (q *Queries) GetClub(ctx context.Context, id string) (Club, error) {
	row := q.db.QueryRowContext(ctx, getClub, id)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarIcon,
		&i.AvatarColor,
		&i.JoinCode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getClubAdminCount = `-- name: GetClubAdminCount :one
SELECT COUNT(*) FROM club_members WHERE club_id = ? AND role = 'admin'
`

func (q *Queries) GetClubAdminCount(ctx context.Context, clubID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getClubAdminCount, clubID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClubByJoinCode = `-- name: GetClubByJoinCode :one
SELECT id, name, description, avatar_icon, avatar_color, join_code, created_by, created_at
FROM clubs WHERE join_code = ?
`

func (q *Queries) GetClubByJoinCode(ctx context.Context, joinCode string) (Club, error) {
	row := q.db.QueryRowContext(ctx, getClubByJoinCode, joinCode)
	var i Club
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarIcon,
		&i.AvatarColor,
		&i.JoinCode,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getClubEvents = `-- name: GetClubEvents :many
SELECT
    s.id,
    CAST(COALESCE(NULLIF(s.name, ''), 'OpenPadel') AS TEXT) AS name,
    s.status,
    s.game_mode,
    s.courts,
    COUNT(p.id) AS player_count,
    s.scheduled_at
FROM sessions s
LEFT JOIN players p ON p.session_id = s.id AND p.active = 1
WHERE s.club_id = ? AND s.status IN ('lobby', 'playing')
GROUP BY s.id
ORDER BY COALESCE(s.scheduled_at, s.created_at) ASC
`

type GetClubEventsRow struct {
	ID          string
	Name        string
	Status      string
	GameMode    string
	Courts      int64
	PlayerCount int64
	ScheduledAt sql.NullString
}

func (q *Queries) GetClubEvents(ctx context.Context, clubID sql.NullString) ([]GetClubEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getClubEvents, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClubEventsRow{}
	for rows.Next() {
		var i GetClubEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.GameMode,
			&i.Courts,
			&i.PlayerCount,
			&i.ScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClubMember = `-- name: GetClubMember :one
SELECT cm.user_id, cm.role, cm.joined_at
FROM club_members cm
WHERE cm.club_id = ? AND cm.user_id = ?
`

type GetClubMemberParams struct {
	ClubID string
	UserID string
}

type GetClubMemberRow struct {
	UserID   string
	Role     string
	JoinedAt string
}

func (q *Queries) GetClubMember(ctx context.Context, arg GetClubMemberParams) (GetClubMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getClubMember, arg.ClubID, arg.UserID)
	var i GetClubMemberRow
	err := row.Scan(&i.UserID, &i.Role, &i.JoinedAt)
	return i, err
}

const getClubMemberCount = `-- name: GetClubMemberCount :one
SELECT COUNT(*) FROM club_members WHERE club_id = ?
`

func (q *Queries) GetClubMemberCount(ctx context.Context, clubID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getClubMemberCount, clubID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClubMembers = `-- name: GetClubMembers :many
SELECT cm.user_id, cm.role, u.display_name, u.avatar_icon, u.avatar_color, cm.joined_at
FROM club_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.club_id = ?
ORDER BY cm.joined_at ASC
`

type GetClubMembersRow struct {
	UserID      string
	Role        string
	DisplayName string
	AvatarIcon  string
	AvatarColor string
	JoinedAt    string
}

func (q *Queries) GetClubMembers(ctx context.Context, clubID string) ([]GetClubMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getClubMembers, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClubMembersRow{}
	for rows.Next() {
		var i GetClubMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.DisplayName,
			&i.AvatarIcon,
			&i.AvatarColor,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserClubs = `-- name: GetUserClubs :many
SELECT DISTINCT c.id, c.name, c.description, c.avatar_icon, c.avatar_color, c.join_code, c.created_by, c.created_at
FROM clubs c
JOIN club_members cm ON cm.club_id = c.id
WHERE cm.user_id = ?
ORDER BY c.created_at DESC
`

func (q *Queries) GetUserClubs(ctx context.Context, userID string) ([]Club, error) {
	rows, err := q.db.QueryContext(ctx, getUserClubs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Club{}
	for rows.Next() {
		var i Club
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarIcon,
			&i.AvatarColor,
			&i.JoinCode,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClubMember = `-- name: InsertClubMember :exec
INSERT INTO club_members (club_id, user_id, role, joined_at)
VALUES (?, ?, ?, ?)
`

type InsertClubMemberParams struct {
	ClubID   string
	UserID   string
	Role     string
	JoinedAt string
}

func (q *Queries) InsertClubMember(ctx context.Context, arg InsertClubMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertClubMember,
		arg.ClubID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const updateClub = `-- name: UpdateClub :exec
UPDATE clubs SET name = ?, description = ?, avatar_icon = ?, avatar_color = ?
WHERE id = ?
`

type UpdateClubParams struct {
	Name        string
	Description string
	AvatarIcon  string
	AvatarColor string
	ID          string
}

func (q *Queries) UpdateClub(ctx context.Context, arg UpdateClubParams) error {
	_, err := q.db.ExecContext(ctx, updateClub,
		arg.Name,
		arg.Description,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.ID,
	)
	return err
}

const updateClubMemberRole = `-- name: UpdateClubMemberRole :exec
UPDATE club_members SET role = ? WHERE club_id = ? AND user_id = ?
`

type UpdateClubMemberRoleParams struct {
	Role   string
	ClubID string
	UserID string
}

func (q *Queries) UpdateClubMemberRole(ctx context.Context, arg UpdateClubMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateClubMemberRole, arg.Role, arg.ClubID, arg.UserID)
	return err
}

const updateJoinCode = `-- name: UpdateJoinCode :exec
UPDATE clubs SET join_code = ? WHERE id = ?
`

type UpdateJoinCodeParams struct {
	JoinCode string
	ID       string
}

func (q *Queries) UpdateJoinCode(ctx context.Context, arg UpdateJoinCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateJoinCode, arg.JoinCode, arg.ID)
	return err
}
