// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"
)

const addContact = `-- name: AddContact :exec
INSERT INTO contacts (user_id, contact_user_id, created_at) VALUES (?, ?, ?)
`

type AddContactParams struct {
	UserID        string
	ContactUserID string
	CreatedAt     string
}

func (q *Queries) AddContact(ctx context.Context, arg AddContactParams) error {
	_, err := q.db.ExecContext(ctx, addContact, arg.UserID, arg.ContactUserID, arg.CreatedAt)
	return err
}

const getContactsByUserID = `-- name: GetContactsByUserID :many
SELECT contact_user_id FROM contacts WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetContactsByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getContactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var contact_user_id string
		if err := rows.Scan(&contact_user_id); err != nil {
			return nil, err
		}
		items = append(items, contact_user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeContact = `-- name: RemoveContact :exec
DELETE FROM contacts WHERE user_id = ? AND contact_user_id = ?
`

type RemoveContactParams struct {
	UserID        string
	ContactUserID string
}

func (q *Queries) RemoveContact(ctx context.Context, arg RemoveContactParams) error {
	_, err := q.db.ExecContext(ctx, removeContact, arg.UserID, arg.ContactUserID)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, display_name, avatar_icon, avatar_color FROM users
WHERE display_name LIKE ? AND id != ?
ORDER BY display_name LIMIT ?
`

type SearchUsersParams struct {
	DisplayName string
	ID          string
	Limit       int64
}

type SearchUsersRow struct {
	ID          string
	Email       string
	DisplayName string
	AvatarIcon  string
	AvatarColor string
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.DisplayName, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarIcon,
			&i.AvatarColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
