// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"
)

const addContact = `-- name: AddContact :exec
INSERT INTO contacts (user_id, contact_user_id, created_at) VALUES (?, ?, ?)
`

type AddContactParams struct {
	UserID        string
	ContactUserID string
	CreatedAt     string
}

func (q *Queries) AddContact(ctx context.Context, arg AddContactParams) error {
	_, err := q.db.ExecContext(ctx, addContact, arg.UserID, arg.ContactUserID, arg.CreatedAt)
	return err
}

const getContacts = `-- name: GetContacts :many
SELECT
    c.contact_user_id,
    u.display_name,
    u.avatar_icon,
    u.avatar_color,
    c.created_at
FROM contacts c
JOIN users u ON u.id = c.contact_user_id
WHERE c.user_id = ?
ORDER BY c.created_at DESC
`

type GetContactsRow struct {
	ContactUserID string
	DisplayName   string
	AvatarIcon    string
	AvatarColor   string
	CreatedAt     string
}

func (q *Queries) GetContacts(ctx context.Context, userID string) ([]GetContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, getContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContactsRow{}
	for rows.Next() {
		var i GetContactsRow
		if err := rows.Scan(
			&i.ContactUserID,
			&i.DisplayName,
			&i.AvatarIcon,
			&i.AvatarColor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeContact = `-- name: RemoveContact :exec
DELETE FROM contacts WHERE user_id = ? AND contact_user_id = ?
`

type RemoveContactParams struct {
	UserID        string
	ContactUserID string
}

func (q *Queries) RemoveContact(ctx context.Context, arg RemoveContactParams) error {
	_, err := q.db.ExecContext(ctx, removeContact, arg.UserID, arg.ContactUserID)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT
    u.id,
    u.email,
    u.display_name,
    u.avatar_icon,
    u.avatar_color,
    CASE WHEN c.contact_user_id IS NOT NULL THEN 1 ELSE 0 END AS is_contact
FROM users u
LEFT JOIN contacts c ON c.contact_user_id = u.id AND c.user_id = ?
WHERE u.display_name LIKE ? AND u.id != ?
ORDER BY u.display_name LIMIT ?
`

type SearchUsersParams struct {
	UserID      string
	DisplayName string
	ID          string
	Limit       int64
}

type SearchUsersRow struct {
	ID          string
	Email       string
	DisplayName string
	AvatarIcon  string
	AvatarColor string
	IsContact   int64
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers,
		arg.UserID,
		arg.DisplayName,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarIcon,
			&i.AvatarColor,
			&i.IsContact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userExists = `-- name: UserExists :one
SELECT COUNT(*) FROM users WHERE id = ?
`

func (q *Queries) UserExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}
