// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"
	"database/sql"
)

const acceptInvite = `-- name: AcceptInvite :exec
INSERT INTO players (id, session_id, user_id, name, avatar_icon, avatar_color, active, joined_at) VALUES (?, ?, ?, ?, ?, ?, 1, ?)
`

type AcceptInviteParams struct {
	ID          string
	SessionID   string
	UserID      sql.NullString
	Name        string
	AvatarIcon  string
	AvatarColor string
	JoinedAt    string
}

func (q *Queries) AcceptInvite(ctx context.Context, arg AcceptInviteParams) error {
	_, err := q.db.ExecContext(ctx, acceptInvite,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Name,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.JoinedAt,
	)
	return err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, session_id, from_user_id, to_user_id, status, created_at) VALUES (?, ?, ?, ?, 'pending', ?)
`

type CreateInviteParams struct {
	ID         string
	SessionID  string
	FromUserID string
	ToUserID   string
	CreatedAt  string
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.SessionID,
		arg.FromUserID,
		arg.ToUserID,
		arg.CreatedAt,
	)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = ?
`

func (q *Queries) DeleteInvite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const getInvite = `-- name: GetInvite :one
SELECT id, session_id, from_user_id, to_user_id, status FROM invites WHERE id = ?
`

type GetInviteRow struct {
	ID         string
	SessionID  string
	FromUserID string
	ToUserID   string
	Status     string
}

func (q *Queries) GetInvite(ctx context.Context, id string) (GetInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getInvite, id)
	var i GetInviteRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
	)
	return i, err
}

const getInvitesByUserID = `-- name: GetInvitesByUserID :many
SELECT id, session_id, from_user_id, status, created_at FROM invites WHERE to_user_id = ? AND status = 'pending' ORDER BY created_at DESC
`

type GetInvitesByUserIDRow struct {
	ID         string
	SessionID  string
	FromUserID string
	Status     string
	CreatedAt  string
}

func (q *Queries) GetInvitesByUserID(ctx context.Context, toUserID string) ([]GetInvitesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvitesByUserID, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInvitesByUserIDRow{}
	for rows.Next() {
		var i GetInvitesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FromUserID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingInvitesBySessionID = `-- name: GetPendingInvitesBySessionID :many
SELECT id, from_user_id, to_user_id, status, created_at FROM invites WHERE session_id = ? AND status = 'pending' ORDER BY created_at DESC
`

type GetPendingInvitesBySessionIDRow struct {
	ID         string
	FromUserID string
	ToUserID   string
	Status     string
	CreatedAt  string
}

func (q *Queries) GetPendingInvitesBySessionID(ctx context.Context, sessionID string) ([]GetPendingInvitesBySessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingInvitesBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingInvitesBySessionIDRow{}
	for rows.Next() {
		var i GetPendingInvitesBySessionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInviteStatus = `-- name: UpdateInviteStatus :exec
UPDATE invites SET status = ? WHERE id = ?
`

type UpdateInviteStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInviteStatus, arg.Status, arg.ID)
	return err
}
