// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"
	"database/sql"
)

const acceptInvite = `-- name: AcceptInvite :exec
INSERT INTO players (id, session_id, user_id, name, avatar_icon, avatar_color, active, joined_at) VALUES (?, ?, ?, ?, ?, ?, 1, ?)
`

type AcceptInviteParams struct {
	ID          string
	SessionID   string
	UserID      sql.NullString
	Name        string
	AvatarIcon  string
	AvatarColor string
	JoinedAt    string
}

func (q *Queries) AcceptInvite(ctx context.Context, arg AcceptInviteParams) error {
	_, err := q.db.ExecContext(ctx, acceptInvite,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Name,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.JoinedAt,
	)
	return err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, session_id, from_user_id, to_user_id, status, created_at) VALUES (?, ?, ?, ?, 'pending', ?)
`

type CreateInviteParams struct {
	ID         string
	SessionID  string
	FromUserID string
	ToUserID   string
	CreatedAt  string
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.SessionID,
		arg.FromUserID,
		arg.ToUserID,
		arg.CreatedAt,
	)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = ?
`

func (q *Queries) DeleteInvite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const getInvite = `-- name: GetInvite :one
SELECT
    i.id,
    i.session_id,
    s.name AS session_name,
    i.from_user_id,
    fu.display_name AS from_display_name,
    fu.avatar_icon AS from_avatar_icon,
    fu.avatar_color AS from_avatar_color,
    i.to_user_id,
    i.status,
    i.created_at
FROM invites i
JOIN sessions s ON s.id = i.session_id
JOIN users fu ON fu.id = i.from_user_id
WHERE i.id = ?
`

type GetInviteRow struct {
	ID              string
	SessionID       string
	SessionName     string
	FromUserID      string
	FromDisplayName string
	FromAvatarIcon  string
	FromAvatarColor string
	ToUserID        string
	Status          string
	CreatedAt       string
}

func (q *Queries) GetInvite(ctx context.Context, id string) (GetInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getInvite, id)
	var i GetInviteRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SessionName,
		&i.FromUserID,
		&i.FromDisplayName,
		&i.FromAvatarIcon,
		&i.FromAvatarColor,
		&i.ToUserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitesByUserID = `-- name: GetInvitesByUserID :many
SELECT
    i.id,
    i.session_id,
    s.name AS session_name,
    i.from_user_id,
    fu.display_name AS from_display_name,
    i.status,
    i.created_at
FROM invites i
JOIN sessions s ON s.id = i.session_id
JOIN users fu ON fu.id = i.from_user_id
WHERE i.to_user_id = ? AND i.status = 'pending'
ORDER BY i.created_at DESC
`

type GetInvitesByUserIDRow struct {
	ID              string
	SessionID       string
	SessionName     string
	FromUserID      string
	FromDisplayName string
	Status          string
	CreatedAt       string
}

func (q *Queries) GetInvitesByUserID(ctx context.Context, toUserID string) ([]GetInvitesByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvitesByUserID, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInvitesByUserIDRow{}
	for rows.Next() {
		var i GetInvitesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SessionName,
			&i.FromUserID,
			&i.FromDisplayName,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingInvitesBySessionID = `-- name: GetPendingInvitesBySessionID :many
SELECT
    i.id,
    i.from_user_id,
    fu.display_name AS from_display_name,
    i.to_user_id,
    tu.display_name AS to_display_name,
    i.status,
    i.created_at
FROM invites i
JOIN users fu ON fu.id = i.from_user_id
JOIN users tu ON tu.id = i.to_user_id
WHERE i.session_id = ? AND i.status = 'pending'
ORDER BY i.created_at DESC
`

type GetPendingInvitesBySessionIDRow struct {
	ID              string
	FromUserID      string
	FromDisplayName string
	ToUserID        string
	ToDisplayName   string
	Status          string
	CreatedAt       string
}

func (q *Queries) GetPendingInvitesBySessionID(ctx context.Context, sessionID string) ([]GetPendingInvitesBySessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingInvitesBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingInvitesBySessionIDRow{}
	for rows.Next() {
		var i GetPendingInvitesBySessionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.FromDisplayName,
			&i.ToUserID,
			&i.ToDisplayName,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInviteStatus = `-- name: UpdateInviteStatus :exec
UPDATE invites SET status = ? WHERE id = ?
`

type UpdateInviteStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInviteStatus, arg.Status, arg.ID)
	return err
}
