// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AuthToken struct {
	Token     string
	UserID    string
	CreatedAt string
}

type Bench struct {
	RoundID  string
	PlayerID string
}

type Contact struct {
	UserID        string
	ContactUserID string
	CreatedAt     string
}

type Invite struct {
	ID         string
	SessionID  string
	FromUserID string
	ToUserID   string
	Status     string
	CreatedAt  string
}

type Match struct {
	ID      string
	RoundID string
	Court   int64
	P1      string
	P2      string
	P3      string
	P4      string
	ScoreA  sql.NullInt64
	ScoreB  sql.NullInt64
	LiveA   sql.NullInt64
	LiveB   sql.NullInt64
	Server  sql.NullString
}

type PasswordResetToken struct {
	TokenHash string
	UserID    string
	ExpiresAt string
}

type Player struct {
	ID          string
	SessionID   string
	Name        string
	Active      int64
	JoinedAt    string
	UserID      sql.NullString
	AvatarIcon  string
	AvatarColor string
}

type PushSubscription struct {
	ID        string
	UserID    string
	Endpoint  string
	P256dh    string
	Auth      string
	CreatedAt string
}

type Round struct {
	ID        string
	SessionID string
	Number    int64
}

type Session struct {
	ID                   string
	AdminToken           string
	Status               string
	Courts               int64
	Points               int64
	RoundsTotal          sql.NullInt64
	CreatorPlayerID      sql.NullString
	CreatedAt            string
	UpdatedAt            string
	CurrentRound         int64
	Name                 string
	ScheduledAt          sql.NullString
	GameMode             string
	SetsToWin            int64
	GamesPerSet          int64
	EndedEarly           int64
	CourtDurationMinutes sql.NullInt64
	EndsAt               sql.NullString
	CreatorUserID        sql.NullString
}

type TennisMatch struct {
	ID        string
	SessionID string
	State     string
	CreatedAt string
	UpdatedAt string
}

type TennisTeam struct {
	SessionID string
	PlayerID  string
	Team      string
}

type User struct {
	ID           string
	Email        string
	DisplayName  string
	PasswordHash string
	CreatedAt    string
	AvatarIcon   string
	AvatarColor  string
}
