// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package db

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (id, session_id, user_id, name, avatar_icon, avatar_color, active, joined_at)
VALUES (?, ?, ?, ?, ?, ?, 1, ?)
`

type CreatePlayerParams struct {
	ID          string
	SessionID   string
	UserID      sql.NullString
	Name        string
	AvatarIcon  string
	AvatarColor string
	JoinedAt    string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) error {
	_, err := q.db.ExecContext(ctx, createPlayer,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Name,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.JoinedAt,
	)
	return err
}

const deactivatePlayer = `-- name: DeactivatePlayer :exec
UPDATE players SET active = 0 WHERE id = ?
`

func (q *Queries) DeactivatePlayer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deactivatePlayer, id)
	return err
}

const getCreatorName = `-- name: GetCreatorName :one
SELECT p.name FROM players p
JOIN sessions s ON s.creator_player_id = p.id
WHERE s.id = ?
`

func (q *Queries) GetCreatorName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCreatorName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getPlayersBySessionID = `-- name: GetPlayersBySessionID :many
SELECT id, session_id, COALESCE(user_id, ''), name, avatar_icon, avatar_color, active, joined_at
FROM players WHERE session_id = ? ORDER BY joined_at
`

type GetPlayersBySessionIDRow struct {
	ID          string
	SessionID   string
	UserID      string
	Name        string
	AvatarIcon  string
	AvatarColor string
	Active      int64
	JoinedAt    string
}

func (q *Queries) GetPlayersBySessionID(ctx context.Context, sessionID string) ([]GetPlayersBySessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayersBySessionIDRow{}
	for rows.Next() {
		var i GetPlayersBySessionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Name,
			&i.AvatarIcon,
			&i.AvatarColor,
			&i.Active,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAvatarByUserID = `-- name: GetUserAvatarByUserID :one
SELECT avatar_icon, avatar_color FROM users WHERE id = ?
`

type GetUserAvatarByUserIDRow struct {
	AvatarIcon  string
	AvatarColor string
}

func (q *Queries) GetUserAvatarByUserID(ctx context.Context, id string) (GetUserAvatarByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAvatarByUserID, id)
	var i GetUserAvatarByUserIDRow
	err := row.Scan(&i.AvatarIcon, &i.AvatarColor)
	return i, err
}
