// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push.sql

package db

import (
	"context"
)

const createPushSubscription = `-- name: CreatePushSubscription :exec
INSERT INTO push_subscriptions (id, user_id, endpoint, p256dh, auth, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePushSubscriptionParams struct {
	ID        string
	UserID    string
	Endpoint  string
	P256dh    string
	Auth      string
	CreatedAt string
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createPushSubscription,
		arg.ID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.CreatedAt,
	)
	return err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE endpoint = ? AND p256dh = ? AND auth = ?
`

type DeletePushSubscriptionParams struct {
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscription, arg.Endpoint, arg.P256dh, arg.Auth)
	return err
}

const getPushSubscriptionsByUserID = `-- name: GetPushSubscriptionsByUserID :many
SELECT id, endpoint, p256dh, auth FROM push_subscriptions WHERE user_id = ?
`

type GetPushSubscriptionsByUserIDRow struct {
	ID       string
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) GetPushSubscriptionsByUserID(ctx context.Context, userID string) ([]GetPushSubscriptionsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPushSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPushSubscriptionsByUserIDRow{}
	for rows.Next() {
		var i GetPushSubscriptionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
