// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AcceptInvite(ctx context.Context, arg AcceptInviteParams) error
	AddContact(ctx context.Context, arg AddContactParams) error
	AdvanceMexicanoRound(ctx context.Context, arg AdvanceMexicanoRoundParams) error
	AdvanceRound(ctx context.Context, arg AdvanceRoundParams) error
	AllRoundsComplete(ctx context.Context, sessionID string) (int64, error)
	CompleteSession(ctx context.Context, arg CompleteSessionParams) error
	CountUnscored(ctx context.Context, sessionID string) (int64, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error
	CreateClub(ctx context.Context, arg CreateClubParams) error
	CreateClubInvite(ctx context.Context, arg CreateClubInviteParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CurrentRoundAllScored(ctx context.Context, id string) (int64, error)
	DeactivatePlayer(ctx context.Context, id string) error
	DeleteAuthToken(ctx context.Context, tokenHash string) error
	DeleteAuthTokensByUserID(ctx context.Context, userID string) error
	DeleteBench(ctx context.Context, sessionID string) error
	DeleteClub(ctx context.Context, id string) error
	DeleteClubMember(ctx context.Context, arg DeleteClubMemberParams) error
	DeleteInvite(ctx context.Context, id string) error
	DeleteMatches(ctx context.Context, sessionID string) error
	DeletePasswordResetToken(ctx context.Context, tokenHash string) error
	DeletePasswordResetTokensByUserID(ctx context.Context, userID string) error
	DeletePlayers(ctx context.Context, sessionID string) error
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error
	DeleteRounds(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteStalePushSubscription(ctx context.Context, endpoint string) error
	DeleteUser(ctx context.Context, id string) error
	GetAuthTokenByHash(ctx context.Context, tokenHash string) (GetAuthTokenByHashRow, error)
	GetBenchByRoundID(ctx context.Context, roundID string) ([]string, error)
	// Cross-mode career summary: games played, wins, and mean per-Match point-share.
	// point_share is the average of yourTeamScore / (yourTeamScore + opponentTeamScore)
	// over every fully-scored Match in a done Session, each match weighted equally
	// regardless of its points target (ADR 0007). Guests fill seats but only the
	// user's own player rows are aggregated.
	GetCareerSummary(ctx context.Context, userID sql.NullString) (GetCareerSummaryRow, error)
	GetClub(ctx context.Context, id string) (Club, error)
	GetClubAdminCount(ctx context.Context, clubID string) (int64, error)
	GetClubByJoinCode(ctx context.Context, joinCode string) (Club, error)
	GetClubEvents(ctx context.Context, clubID sql.NullString) ([]GetClubEventsRow, error)
	GetClubInvite(ctx context.Context, id string) (GetClubInviteRow, error)
	GetClubInviteByClubAndInvitee(ctx context.Context, arg GetClubInviteByClubAndInviteeParams) (GetClubInviteByClubAndInviteeRow, error)
	GetClubInvitesByInviteeID(ctx context.Context, inviteeID string) ([]GetClubInvitesByInviteeIDRow, error)
	GetClubMember(ctx context.Context, arg GetClubMemberParams) (GetClubMemberRow, error)
	GetClubMemberCount(ctx context.Context, clubID string) (int64, error)
	GetClubMembers(ctx context.Context, clubID string) ([]GetClubMembersRow, error)
	GetContacts(ctx context.Context, userID string) ([]GetContactsRow, error)
	GetCreatorName(ctx context.Context, id string) (string, error)
	GetCurrentRoundBySessionID(ctx context.Context, sessionID string) (GetCurrentRoundBySessionIDRow, error)
	GetHeadToHead(ctx context.Context, sessionID string) ([]GetHeadToHeadRow, error)
	GetInvite(ctx context.Context, id string) (GetInviteRow, error)
	GetInvitesByUserID(ctx context.Context, toUserID string) ([]GetInvitesByUserIDRow, error)
	GetLastRoundBySessionID(ctx context.Context, sessionID string) (GetLastRoundBySessionIDRow, error)
	GetLeaderboard(ctx context.Context, sessionID string) ([]GetLeaderboardRow, error)
	GetMatchByID(ctx context.Context, id string) (Match, error)
	// Per-Match results series for the Career Stats page's recent-form curve
	// (ADR 0007). One row per fully-scored Match the user played in a done Session,
	// oldest-first (by Session date, then round, then court) so the client reads it
	// as a time series. INNER JOINs on rounds/matches keep out ended-early Sessions
	// with no scored Match. points / conceded are the user's own-team and opponent
	// -team score for that Match; the win/draw/loss outcome is derived in Go. date is
	// the Session date (Matches carry no timestamp of their own). Guests fill seats
	// but only the user's player rows are aggregated.
	GetMatchResultsSeries(ctx context.Context, userID sql.NullString) ([]GetMatchResultsSeriesRow, error)
	GetMatchesByRoundID(ctx context.Context, roundID string) ([]Match, error)
	// Per-Game-Mode career aggregate for the Career Stats page (ADR 0007). One row
	// per Game Mode the user has a done Session in; modes with no history are absent
	// and filled in by the store. point_share is the mean per-Match share (same as
	// GetCareerSummary) but grouped by mode, since point-share only compares like-for
	// -like within one scoring model. total_points / points_conceded are the user's
	// own-team and opponent-team score totals across fully-scored matches. tournaments
	// counts distinct done Sessions the user joined in that mode. Guests fill seats
	// but only the user's own player rows are aggregated.
	GetModeStats(ctx context.Context, userID sql.NullString) ([]GetModeStatsRow, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (GetPasswordResetTokenRow, error)
	GetPendingInvitesBySessionID(ctx context.Context, sessionID string) ([]GetPendingInvitesBySessionIDRow, error)
	GetPlayerTokenHash(ctx context.Context, id string) (string, error)
	GetPlayersBySessionID(ctx context.Context, sessionID string) ([]GetPlayersBySessionIDRow, error)
	GetPushSubscriptionsByUserID(ctx context.Context, userID string) ([]PushSubscription, error)
	GetPushSubscriptionsForSession(ctx context.Context, sessionID string) ([]GetPushSubscriptionsForSessionRow, error)
	GetRoundsBySessionID(ctx context.Context, sessionID string) ([]GetRoundsBySessionIDRow, error)
	GetSession(ctx context.Context, id string) (GetSessionRow, error)
	// Done Sessions the user played, newest first, for both the tournament history
	// timeline and the cross-mode placement stats (ADR 0007). scored is 1 when the
	// user has at least one fully-scored Match in the Session, so placement can
	// ignore ended-early Sessions the user never actually finished a game in; the
	// finishing rank itself is resolved from the leaderboard in Go.
	GetTournamentHistorySessions(ctx context.Context, userID sql.NullString) ([]GetTournamentHistorySessionsRow, error)
	GetUpcomingTournaments(ctx context.Context, userID sql.NullString) ([]GetUpcomingTournamentsRow, error)
	GetUserAvatarByUserID(ctx context.Context, id string) (GetUserAvatarByUserIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserClubs(ctx context.Context, userID string) ([]Club, error)
	GetUserSessions(ctx context.Context, creatorUserID sql.NullString) ([]GetUserSessionsRow, error)
	IncrementTournamentWinCount(ctx context.Context, id string) error
	InsertBench(ctx context.Context, arg InsertBenchParams) error
	InsertClubMember(ctx context.Context, arg InsertClubMemberParams) error
	InsertMatch(ctx context.Context, arg InsertMatchParams) error
	InsertRound(ctx context.Context, arg InsertRoundParams) error
	RemoveContact(ctx context.Context, arg RemoveContactParams) error
	ResetClubInvite(ctx context.Context, arg ResetClubInviteParams) error
	SavePushSubscription(ctx context.Context, arg SavePushSubscriptionParams) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	SetCreatorPlayer(ctx context.Context, arg SetCreatorPlayerParams) error
	SetRoundStartedAt(ctx context.Context, arg SetRoundStartedAtParams) error
	StartMexicanoSession(ctx context.Context, arg StartMexicanoSessionParams) error
	StartSession(ctx context.Context, arg StartSessionParams) error
	StartTimedAmericanoSession(ctx context.Context, arg StartTimedAmericanoSessionParams) error
	UpdateAuthTokenExpiry(ctx context.Context, arg UpdateAuthTokenExpiryParams) error
	UpdateClub(ctx context.Context, arg UpdateClubParams) error
	UpdateClubInviteStatus(ctx context.Context, arg UpdateClubInviteStatusParams) error
	UpdateClubMemberRole(ctx context.Context, arg UpdateClubMemberRoleParams) error
	UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) error
	UpdateJoinCode(ctx context.Context, arg UpdateJoinCodeParams) error
	UpdateMatchLiveScore(ctx context.Context, arg UpdateMatchLiveScoreParams) error
	UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) error
	UpdatePlayerRating(ctx context.Context, arg UpdatePlayerRatingParams) error
	UpdatePlayerUserIDToNull(ctx context.Context, userID sql.NullString) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateProfileAvatarOnPlayers(ctx context.Context, arg UpdateProfileAvatarOnPlayersParams) error
	UpdateRoundDuration(ctx context.Context, arg UpdateRoundDurationParams) error
	UpdateSessionConfig(ctx context.Context, arg UpdateSessionConfigParams) error
	UpdateSessionCurrentRound(ctx context.Context, arg UpdateSessionCurrentRoundParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserSelfRating(ctx context.Context, arg UpdateUserSelfRatingParams) error
	UserExists(ctx context.Context, id string) (int64, error)
}

var _ Querier = (*Queries)(nil)
