// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AcceptInvite(ctx context.Context, arg AcceptInviteParams) error
	AddContact(ctx context.Context, arg AddContactParams) error
	AdvanceMexicanoRound(ctx context.Context, arg AdvanceMexicanoRoundParams) error
	AdvanceRound(ctx context.Context, arg AdvanceRoundParams) error
	AllRoundsComplete(ctx context.Context, sessionID string) (int64, error)
	CompleteSession(ctx context.Context, arg CompleteSessionParams) error
	CountUnscored(ctx context.Context, sessionID string) (int64, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CurrentRoundAllScored(ctx context.Context, id string) (int64, error)
	DeactivatePlayer(ctx context.Context, id string) error
	DeleteAuthToken(ctx context.Context, token string) error
	DeleteAuthTokensByUserID(ctx context.Context, userID string) error
	DeleteBench(ctx context.Context, sessionID string) error
	DeleteInvite(ctx context.Context, id string) error
	DeleteMatches(ctx context.Context, sessionID string) error
	DeletePasswordResetToken(ctx context.Context, tokenHash string) error
	DeletePasswordResetTokensByUserID(ctx context.Context, userID string) error
	DeletePlayers(ctx context.Context, sessionID string) error
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error
	DeleteRounds(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteStalePushSubscription(ctx context.Context, endpoint string) error
	DeleteUser(ctx context.Context, id string) error
	GetAmericanoCareerStats(ctx context.Context, userID sql.NullString) (GetAmericanoCareerStatsRow, error)
	GetBenchByRoundID(ctx context.Context, roundID string) ([]string, error)
	GetContacts(ctx context.Context, userID string) ([]GetContactsRow, error)
	GetCreatorName(ctx context.Context, id string) (string, error)
	GetCurrentRoundBySessionID(ctx context.Context, sessionID string) (GetCurrentRoundBySessionIDRow, error)
	GetHeadToHead(ctx context.Context, sessionID string) ([]GetHeadToHeadRow, error)
	GetInvite(ctx context.Context, id string) (GetInviteRow, error)
	GetInvitesByUserID(ctx context.Context, toUserID string) ([]GetInvitesByUserIDRow, error)
	GetLastRoundBySessionID(ctx context.Context, sessionID string) (GetLastRoundBySessionIDRow, error)
	GetLeaderboard(ctx context.Context, sessionID string) ([]GetLeaderboardRow, error)
	GetMatchByID(ctx context.Context, id string) (Match, error)
	GetMatchesByRoundID(ctx context.Context, roundID string) ([]Match, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (GetPasswordResetTokenRow, error)
	GetPendingInvitesBySessionID(ctx context.Context, sessionID string) ([]GetPendingInvitesBySessionIDRow, error)
	GetPlayersBySessionID(ctx context.Context, sessionID string) ([]GetPlayersBySessionIDRow, error)
	GetPushSubscriptionsByUserID(ctx context.Context, userID string) ([]PushSubscription, error)
	GetPushSubscriptionsForSession(ctx context.Context, sessionID string) ([]GetPushSubscriptionsForSessionRow, error)
	GetRoundsBySessionID(ctx context.Context, sessionID string) ([]GetRoundsBySessionIDRow, error)
	GetSession(ctx context.Context, id string) (GetSessionRow, error)
	GetTournamentHistorySessions(ctx context.Context, userID sql.NullString) ([]GetTournamentHistorySessionsRow, error)
	GetUpcomingTournaments(ctx context.Context, userID sql.NullString) ([]GetUpcomingTournamentsRow, error)
	GetUserAvatarByUserID(ctx context.Context, id string) (GetUserAvatarByUserIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserIDByToken(ctx context.Context, token string) (string, error)
	IncrementTournamentWinCount(ctx context.Context, id string) error
	InsertBench(ctx context.Context, arg InsertBenchParams) error
	InsertMatch(ctx context.Context, arg InsertMatchParams) error
	InsertRound(ctx context.Context, arg InsertRoundParams) error
	RemoveContact(ctx context.Context, arg RemoveContactParams) error
	SavePushSubscription(ctx context.Context, arg SavePushSubscriptionParams) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	SetCreatorPlayer(ctx context.Context, arg SetCreatorPlayerParams) error
	SetRoundStartedAt(ctx context.Context, arg SetRoundStartedAtParams) error
	StartMexicanoSession(ctx context.Context, arg StartMexicanoSessionParams) error
	StartSession(ctx context.Context, arg StartSessionParams) error
	StartTimedAmericanoSession(ctx context.Context, arg StartTimedAmericanoSessionParams) error
	UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) error
	UpdateMatchLiveScore(ctx context.Context, arg UpdateMatchLiveScoreParams) error
	UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) error
	UpdatePlayerUserIDToNull(ctx context.Context, userID sql.NullString) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateProfileAvatarOnPlayers(ctx context.Context, arg UpdateProfileAvatarOnPlayersParams) error
	UpdateRoundDuration(ctx context.Context, arg UpdateRoundDurationParams) error
	UpdateSessionCurrentRound(ctx context.Context, arg UpdateSessionCurrentRoundParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UserExists(ctx context.Context, id string) (int64, error)
}

var _ Querier = (*Queries)(nil)
