// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds.sql

package db

import (
	"context"
	"database/sql"
)

const advanceMexicanoRound = `-- name: AdvanceMexicanoRound :exec
INSERT INTO rounds (id, session_id, number) VALUES (?, ?, ?)
`

type AdvanceMexicanoRoundParams struct {
	ID        string
	SessionID string
	Number    int64
}

func (q *Queries) AdvanceMexicanoRound(ctx context.Context, arg AdvanceMexicanoRoundParams) error {
	_, err := q.db.ExecContext(ctx, advanceMexicanoRound, arg.ID, arg.SessionID, arg.Number)
	return err
}

const allRoundsComplete = `-- name: AllRoundsComplete :one
SELECT COUNT(*) FROM matches m
JOIN rounds r ON r.id = m.round_id
WHERE r.session_id = ? AND m.score_a IS NULL
`

func (q *Queries) AllRoundsComplete(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, allRoundsComplete, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnscored = `-- name: CountUnscored :one
SELECT COUNT(*) FROM matches m
JOIN rounds r ON r.id = m.round_id
WHERE r.session_id = ? AND m.score_a IS NULL
`

func (q *Queries) CountUnscored(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnscored, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBenchByRoundID = `-- name: GetBenchByRoundID :many
SELECT player_id FROM bench WHERE round_id = ?
`

func (q *Queries) GetBenchByRoundID(ctx context.Context, roundID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBenchByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var player_id string
		if err := rows.Scan(&player_id); err != nil {
			return nil, err
		}
		items = append(items, player_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentRoundBySessionID = `-- name: GetCurrentRoundBySessionID :one
SELECT r.id, r.number FROM rounds r
JOIN sessions sess ON sess.id = r.session_id
WHERE r.session_id = ? AND r.number = sess.current_round
`

type GetCurrentRoundBySessionIDRow struct {
	ID     string
	Number int64
}

func (q *Queries) GetCurrentRoundBySessionID(ctx context.Context, sessionID string) (GetCurrentRoundBySessionIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentRoundBySessionID, sessionID)
	var i GetCurrentRoundBySessionIDRow
	err := row.Scan(&i.ID, &i.Number)
	return i, err
}

const getHeadToHead = `-- name: GetHeadToHead :many
SELECT m.p1, m.p2, m.p3, m.p4, m.score_a, m.score_b
FROM matches m
JOIN rounds r ON r.id = m.round_id
WHERE r.session_id = ? AND m.score_a IS NOT NULL
`

type GetHeadToHeadRow struct {
	P1     string
	P2     string
	P3     string
	P4     string
	ScoreA sql.NullInt64
	ScoreB sql.NullInt64
}

func (q *Queries) GetHeadToHead(ctx context.Context, sessionID string) ([]GetHeadToHeadRow, error) {
	rows, err := q.db.QueryContext(ctx, getHeadToHead, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHeadToHeadRow{}
	for rows.Next() {
		var i GetHeadToHeadRow
		if err := rows.Scan(
			&i.P1,
			&i.P2,
			&i.P3,
			&i.P4,
			&i.ScoreA,
			&i.ScoreB,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastRoundBySessionID = `-- name: GetLastRoundBySessionID :one
SELECT id, number FROM rounds WHERE session_id = ? ORDER BY number DESC LIMIT 1
`

type GetLastRoundBySessionIDRow struct {
	ID     string
	Number int64
}

func (q *Queries) GetLastRoundBySessionID(ctx context.Context, sessionID string) (GetLastRoundBySessionIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLastRoundBySessionID, sessionID)
	var i GetLastRoundBySessionIDRow
	err := row.Scan(&i.ID, &i.Number)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT
    p.id,
    p.user_id,
    p.name,
    CAST(COALESCE(SUM(CASE WHEN m.p1 = p.id OR m.p2 = p.id THEN m.score_a WHEN m.p3 = p.id OR m.p4 = p.id THEN m.score_b ELSE 0 END), 0) AS INTEGER) AS points,
    CAST(COALESCE(SUM(CASE WHEN m.p1 = p.id OR m.p2 = p.id THEN m.score_b WHEN m.p3 = p.id OR m.p4 = p.id THEN m.score_a ELSE 0 END), 0) AS INTEGER) AS points_conceded,
    COUNT(m.id) AS games_played,
    CAST(COALESCE(SUM(CASE WHEN (m.p1 = p.id OR m.p2 = p.id) AND m.score_a > m.score_b THEN 1 WHEN (m.p3 = p.id OR m.p4 = p.id) AND m.score_b > m.score_a THEN 1 ELSE 0 END), 0) AS INTEGER) AS wins,
    CAST(COALESCE(SUM(CASE WHEN m.score_a = m.score_b THEN 1 ELSE 0 END), 0) AS INTEGER) AS draws,
    p.avatar_icon,
    p.avatar_color
FROM players p
LEFT JOIN rounds r ON r.session_id = p.session_id
LEFT JOIN matches m ON m.round_id = r.id
    AND (m.p1 = p.id OR m.p2 = p.id OR m.p3 = p.id OR m.p4 = p.id)
    AND m.score_a IS NOT NULL
WHERE p.session_id = ? AND p.active = 1
GROUP BY p.id, p.name
`

type GetLeaderboardRow struct {
	ID             string
	UserID         sql.NullString
	Name           string
	Points         int64
	PointsConceded int64
	GamesPlayed    int64
	Wins           int64
	Draws          int64
	AvatarIcon     string
	AvatarColor    string
}

func (q *Queries) GetLeaderboard(ctx context.Context, sessionID string) ([]GetLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboard, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardRow{}
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Points,
			&i.PointsConceded,
			&i.GamesPlayed,
			&i.Wins,
			&i.Draws,
			&i.AvatarIcon,
			&i.AvatarColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, round_id, court, p1, p2, p3, p4, score_a, score_b, live_a, live_b, server FROM matches WHERE id = ?
`

func (q *Queries) GetMatchByID(ctx context.Context, id string) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.Court,
		&i.P1,
		&i.P2,
		&i.P3,
		&i.P4,
		&i.ScoreA,
		&i.ScoreB,
		&i.LiveA,
		&i.LiveB,
		&i.Server,
	)
	return i, err
}

const getMatchesByRoundID = `-- name: GetMatchesByRoundID :many
SELECT id, round_id, court, p1, p2, p3, p4, score_a, score_b, live_a, live_b, server FROM matches WHERE round_id = ? ORDER BY court
`

func (q *Queries) GetMatchesByRoundID(ctx context.Context, roundID string) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getMatchesByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.Court,
			&i.P1,
			&i.P2,
			&i.P3,
			&i.P4,
			&i.ScoreA,
			&i.ScoreB,
			&i.LiveA,
			&i.LiveB,
			&i.Server,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoundsBySessionID = `-- name: GetRoundsBySessionID :many
SELECT id, number FROM rounds WHERE session_id = ? ORDER BY number
`

type GetRoundsBySessionIDRow struct {
	ID     string
	Number int64
}

func (q *Queries) GetRoundsBySessionID(ctx context.Context, sessionID string) ([]GetRoundsBySessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoundsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoundsBySessionIDRow{}
	for rows.Next() {
		var i GetRoundsBySessionIDRow
		if err := rows.Scan(&i.ID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBench = `-- name: InsertBench :exec
INSERT INTO bench (round_id, player_id) VALUES (?, ?)
`

type InsertBenchParams struct {
	RoundID  string
	PlayerID string
}

func (q *Queries) InsertBench(ctx context.Context, arg InsertBenchParams) error {
	_, err := q.db.ExecContext(ctx, insertBench, arg.RoundID, arg.PlayerID)
	return err
}

const insertMatch = `-- name: InsertMatch :exec
INSERT INTO matches (id, round_id, court, p1, p2, p3, p4) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertMatchParams struct {
	ID      string
	RoundID string
	Court   int64
	P1      string
	P2      string
	P3      string
	P4      string
}

func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) error {
	_, err := q.db.ExecContext(ctx, insertMatch,
		arg.ID,
		arg.RoundID,
		arg.Court,
		arg.P1,
		arg.P2,
		arg.P3,
		arg.P4,
	)
	return err
}

const insertRound = `-- name: InsertRound :exec
INSERT INTO rounds (id, session_id, number) VALUES (?, ?, ?)
`

type InsertRoundParams struct {
	ID        string
	SessionID string
	Number    int64
}

func (q *Queries) InsertRound(ctx context.Context, arg InsertRoundParams) error {
	_, err := q.db.ExecContext(ctx, insertRound, arg.ID, arg.SessionID, arg.Number)
	return err
}

const updateMatchLiveScore = `-- name: UpdateMatchLiveScore :exec
UPDATE matches SET live_a = ?, live_b = ?, server = ? WHERE id = ?
`

type UpdateMatchLiveScoreParams struct {
	LiveA  sql.NullInt64
	LiveB  sql.NullInt64
	Server sql.NullString
	ID     string
}

func (q *Queries) UpdateMatchLiveScore(ctx context.Context, arg UpdateMatchLiveScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateMatchLiveScore,
		arg.LiveA,
		arg.LiveB,
		arg.Server,
		arg.ID,
	)
	return err
}

const updateMatchScore = `-- name: UpdateMatchScore :exec
UPDATE matches SET score_a = ?, score_b = ?, live_a = NULL, live_b = NULL WHERE id = ?
`

type UpdateMatchScoreParams struct {
	ScoreA sql.NullInt64
	ScoreB sql.NullInt64
	ID     string
}

func (q *Queries) UpdateMatchScore(ctx context.Context, arg UpdateMatchScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateMatchScore, arg.ScoreA, arg.ScoreB, arg.ID)
	return err
}

const updateSessionCurrentRound = `-- name: UpdateSessionCurrentRound :exec
UPDATE sessions SET current_round = ?, updated_at = ? WHERE id = ?
`

type UpdateSessionCurrentRoundParams struct {
	CurrentRound int64
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateSessionCurrentRound(ctx context.Context, arg UpdateSessionCurrentRoundParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionCurrentRound, arg.CurrentRound, arg.UpdatedAt, arg.ID)
	return err
}
