// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const advanceRound = `-- name: AdvanceRound :exec
UPDATE sessions SET current_round = current_round + 1, updated_at = ? WHERE id = ?
`

type AdvanceRoundParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) AdvanceRound(ctx context.Context, arg AdvanceRoundParams) error {
	_, err := q.db.ExecContext(ctx, advanceRound, arg.UpdatedAt, arg.ID)
	return err
}

const completeSession = `-- name: CompleteSession :exec
UPDATE sessions SET status = ?, ended_early = ?, updated_at = ? WHERE id = ?
`

type CompleteSessionParams struct {
	Status     string
	EndedEarly int64
	UpdatedAt  string
	ID         string
}

func (q *Queries) CompleteSession(ctx context.Context, arg CompleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, completeSession,
		arg.Status,
		arg.EndedEarly,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, admin_token, status, name, game_mode, sets_to_win, games_per_set, courts, points, rounds_total, scheduled_at, court_duration_minutes, total_duration_minutes, creator_user_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID                   string
	AdminToken           string
	Status               string
	Name                 string
	GameMode             string
	SetsToWin            int64
	GamesPerSet          int64
	Courts               int64
	Points               int64
	RoundsTotal          sql.NullInt64
	ScheduledAt          sql.NullString
	CourtDurationMinutes sql.NullInt64
	TotalDurationMinutes sql.NullInt64
	CreatorUserID        sql.NullString
	CreatedAt            string
	UpdatedAt            string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.AdminToken,
		arg.Status,
		arg.Name,
		arg.GameMode,
		arg.SetsToWin,
		arg.GamesPerSet,
		arg.Courts,
		arg.Points,
		arg.RoundsTotal,
		arg.ScheduledAt,
		arg.CourtDurationMinutes,
		arg.TotalDurationMinutes,
		arg.CreatorUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const currentRoundAllScored = `-- name: CurrentRoundAllScored :one
SELECT COUNT(*) FROM matches m
JOIN rounds r ON r.id = m.round_id
JOIN sessions s ON s.id = r.session_id
WHERE s.id = ? AND r.number = s.current_round AND m.score_a IS NULL
`

func (q *Queries) CurrentRoundAllScored(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, currentRoundAllScored, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBench = `-- name: DeleteBench :exec
DELETE FROM bench WHERE round_id IN (SELECT id FROM rounds WHERE session_id = ?)
`

func (q *Queries) DeleteBench(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteBench, sessionID)
	return err
}

const deleteMatches = `-- name: DeleteMatches :exec
DELETE FROM matches WHERE round_id IN (SELECT id FROM rounds WHERE session_id = ?)
`

func (q *Queries) DeleteMatches(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteMatches, sessionID)
	return err
}

const deletePlayers = `-- name: DeletePlayers :exec
DELETE FROM players WHERE session_id = ?
`

func (q *Queries) DeletePlayers(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deletePlayers, sessionID)
	return err
}

const deleteRounds = `-- name: DeleteRounds :exec
DELETE FROM rounds WHERE session_id = ?
`

func (q *Queries) DeleteRounds(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteRounds, sessionID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, admin_token, status, name, game_mode, sets_to_win, games_per_set, courts, points, rounds_total, creator_player_id, creator_user_id, current_round, scheduled_at, court_duration_minutes, ends_at, total_duration_minutes, round_duration_seconds, round_started_at, created_at, updated_at
FROM sessions WHERE id = ?
`

type GetSessionRow struct {
	ID                   string
	AdminToken           string
	Status               string
	Name                 string
	GameMode             string
	SetsToWin            int64
	GamesPerSet          int64
	Courts               int64
	Points               int64
	RoundsTotal          sql.NullInt64
	CreatorPlayerID      sql.NullString
	CreatorUserID        sql.NullString
	CurrentRound         int64
	ScheduledAt          sql.NullString
	CourtDurationMinutes sql.NullInt64
	EndsAt               sql.NullString
	TotalDurationMinutes sql.NullInt64
	RoundDurationSeconds sql.NullInt64
	RoundStartedAt       sql.NullString
	CreatedAt            string
	UpdatedAt            string
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.AdminToken,
		&i.Status,
		&i.Name,
		&i.GameMode,
		&i.SetsToWin,
		&i.GamesPerSet,
		&i.Courts,
		&i.Points,
		&i.RoundsTotal,
		&i.CreatorPlayerID,
		&i.CreatorUserID,
		&i.CurrentRound,
		&i.ScheduledAt,
		&i.CourtDurationMinutes,
		&i.EndsAt,
		&i.TotalDurationMinutes,
		&i.RoundDurationSeconds,
		&i.RoundStartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCreatorPlayer = `-- name: SetCreatorPlayer :exec
UPDATE sessions SET creator_player_id = ?, updated_at = ? WHERE id = ?
`

type SetCreatorPlayerParams struct {
	CreatorPlayerID sql.NullString
	UpdatedAt       string
	ID              string
}

func (q *Queries) SetCreatorPlayer(ctx context.Context, arg SetCreatorPlayerParams) error {
	_, err := q.db.ExecContext(ctx, setCreatorPlayer, arg.CreatorPlayerID, arg.UpdatedAt, arg.ID)
	return err
}

const setRoundStartedAt = `-- name: SetRoundStartedAt :exec
UPDATE sessions SET round_started_at = ?, updated_at = ? WHERE id = ?
`

type SetRoundStartedAtParams struct {
	RoundStartedAt sql.NullString
	UpdatedAt      string
	ID             string
}

func (q *Queries) SetRoundStartedAt(ctx context.Context, arg SetRoundStartedAtParams) error {
	_, err := q.db.ExecContext(ctx, setRoundStartedAt, arg.RoundStartedAt, arg.UpdatedAt, arg.ID)
	return err
}

const startMexicanoSession = `-- name: StartMexicanoSession :exec
UPDATE sessions SET status = ?, current_round = 1, ends_at = ?, updated_at = ? WHERE id = ?
`

type StartMexicanoSessionParams struct {
	Status    string
	EndsAt    sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) StartMexicanoSession(ctx context.Context, arg StartMexicanoSessionParams) error {
	_, err := q.db.ExecContext(ctx, startMexicanoSession,
		arg.Status,
		arg.EndsAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const startSession = `-- name: StartSession :exec
UPDATE sessions SET status = ?, rounds_total = ?, current_round = 1, ends_at = ?, updated_at = ? WHERE id = ?
`

type StartSessionParams struct {
	Status      string
	RoundsTotal sql.NullInt64
	EndsAt      sql.NullString
	UpdatedAt   string
	ID          string
}

func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) error {
	_, err := q.db.ExecContext(ctx, startSession,
		arg.Status,
		arg.RoundsTotal,
		arg.EndsAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const startTimedAmericanoSession = `-- name: StartTimedAmericanoSession :exec
UPDATE sessions SET status = ?, rounds_total = ?, total_duration_minutes = ?, round_duration_seconds = ?, current_round = 1, ends_at = ?, updated_at = ? WHERE id = ?
`

type StartTimedAmericanoSessionParams struct {
	Status               string
	RoundsTotal          sql.NullInt64
	TotalDurationMinutes sql.NullInt64
	RoundDurationSeconds sql.NullInt64
	EndsAt               sql.NullString
	UpdatedAt            string
	ID                   string
}

func (q *Queries) StartTimedAmericanoSession(ctx context.Context, arg StartTimedAmericanoSessionParams) error {
	_, err := q.db.ExecContext(ctx, startTimedAmericanoSession,
		arg.Status,
		arg.RoundsTotal,
		arg.TotalDurationMinutes,
		arg.RoundDurationSeconds,
		arg.EndsAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateRoundDuration = `-- name: UpdateRoundDuration :exec
UPDATE sessions SET round_duration_seconds = ?, updated_at = ? WHERE id = ?
`

type UpdateRoundDurationParams struct {
	RoundDurationSeconds sql.NullInt64
	UpdatedAt            string
	ID                   string
}

func (q *Queries) UpdateRoundDuration(ctx context.Context, arg UpdateRoundDurationParams) error {
	_, err := q.db.ExecContext(ctx, updateRoundDuration, arg.RoundDurationSeconds, arg.UpdatedAt, arg.ID)
	return err
}

const updateSessionConfig = `-- name: UpdateSessionConfig :exec
UPDATE sessions SET name = ?, game_mode = ?, courts = ?, points = ?, rounds_total = ?, scheduled_at = ?, updated_at = ? WHERE id = ?
`

type UpdateSessionConfigParams struct {
	Name        string
	GameMode    string
	Courts      int64
	Points      int64
	RoundsTotal sql.NullInt64
	ScheduledAt sql.NullString
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateSessionConfig(ctx context.Context, arg UpdateSessionConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionConfig,
		arg.Name,
		arg.GameMode,
		arg.Courts,
		arg.Points,
		arg.RoundsTotal,
		arg.ScheduledAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
