// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tennis.sql

package db

import (
	"context"
)

const createTennisMatch = `-- name: CreateTennisMatch :exec
INSERT INTO tennis_matches (id, session_id, state, created_at, updated_at) VALUES (?, ?, ?, ?, ?)
`

type CreateTennisMatchParams struct {
	ID        string
	SessionID string
	State     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateTennisMatch(ctx context.Context, arg CreateTennisMatchParams) error {
	_, err := q.db.ExecContext(ctx, createTennisMatch,
		arg.ID,
		arg.SessionID,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTennisTeamsBySessionID = `-- name: DeleteTennisTeamsBySessionID :exec
DELETE FROM tennis_teams WHERE session_id = ?
`

func (q *Queries) DeleteTennisTeamsBySessionID(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteTennisTeamsBySessionID, sessionID)
	return err
}

const getTennisMatch = `-- name: GetTennisMatch :one
SELECT id, session_id, state, created_at, updated_at FROM tennis_matches WHERE session_id = ?
`

func (q *Queries) GetTennisMatch(ctx context.Context, sessionID string) (TennisMatch, error) {
	row := q.db.QueryRowContext(ctx, getTennisMatch, sessionID)
	var i TennisMatch
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTennisTeamsBySessionID = `-- name: GetTennisTeamsBySessionID :many
SELECT tt.player_id, p.name, tt.team
FROM tennis_teams tt
JOIN players p ON p.id = tt.player_id
WHERE tt.session_id = ?
`

type GetTennisTeamsBySessionIDRow struct {
	PlayerID string
	Name     string
	Team     string
}

func (q *Queries) GetTennisTeamsBySessionID(ctx context.Context, sessionID string) ([]GetTennisTeamsBySessionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTennisTeamsBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTennisTeamsBySessionIDRow{}
	for rows.Next() {
		var i GetTennisTeamsBySessionIDRow
		if err := rows.Scan(&i.PlayerID, &i.Name, &i.Team); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTennisTeam = `-- name: InsertTennisTeam :exec
INSERT INTO tennis_teams (session_id, player_id, team) VALUES (?, ?, ?)
`

type InsertTennisTeamParams struct {
	SessionID string
	PlayerID  string
	Team      string
}

func (q *Queries) InsertTennisTeam(ctx context.Context, arg InsertTennisTeamParams) error {
	_, err := q.db.ExecContext(ctx, insertTennisTeam, arg.SessionID, arg.PlayerID, arg.Team)
	return err
}

const updateTennisState = `-- name: UpdateTennisState :exec
UPDATE tennis_matches SET state = ?, updated_at = ? WHERE id = ?
`

type UpdateTennisStateParams struct {
	State     string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateTennisState(ctx context.Context, arg UpdateTennisStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTennisState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}
