// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (token, user_id, created_at) VALUES (?, ?, ?)
`

type CreateAuthTokenParams struct {
	Token     string
	UserID    string
	CreatedAt string
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAuthToken, arg.Token, arg.UserID, arg.CreatedAt)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (token_hash, user_id, expires_at) VALUES (?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	TokenHash string
	UserID    string
	ExpiresAt string
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, display_name, avatar_icon, avatar_color, password_hash, self_rating, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        string
	DisplayName  string
	AvatarIcon   string
	AvatarColor  string
	PasswordHash string
	SelfRating   sql.NullInt64
	CreatedAt    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.PasswordHash,
		arg.SelfRating,
		arg.CreatedAt,
	)
	return err
}

const deleteAuthToken = `-- name: DeleteAuthToken :exec
DELETE FROM auth_tokens WHERE token = ?
`

func (q *Queries) DeleteAuthToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthToken, token)
	return err
}

const deleteAuthTokensByUserID = `-- name: DeleteAuthTokensByUserID :exec
DELETE FROM auth_tokens WHERE user_id = ?
`

func (q *Queries) DeleteAuthTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthTokensByUserID, userID)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens WHERE token_hash = ?
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetToken, tokenHash)
	return err
}

const deletePasswordResetTokensByUserID = `-- name: DeletePasswordResetTokensByUserID :exec
DELETE FROM password_reset_tokens WHERE user_id = ?
`

func (q *Queries) DeletePasswordResetTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetTokensByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getCareerSummary = `-- name: GetCareerSummary :one
SELECT
    COUNT(m.id) AS games,
    CAST(COALESCE(SUM(
        CASE
            WHEN (m.p1 = p.id OR m.p2 = p.id) AND m.score_a > m.score_b THEN 1
            WHEN (m.p3 = p.id OR m.p4 = p.id) AND m.score_b > m.score_a THEN 1
            ELSE 0
        END
    ), 0) AS INTEGER) AS wins,
    CAST(COALESCE(AVG(
        CASE
            WHEN (m.score_a + m.score_b) = 0 THEN 0.5
            WHEN (m.p1 = p.id OR m.p2 = p.id) THEN CAST(m.score_a AS REAL) / (m.score_a + m.score_b)
            ELSE CAST(m.score_b AS REAL) / (m.score_a + m.score_b)
        END
    ), 0.0) AS REAL) AS point_share
FROM players p
JOIN sessions s ON s.id = p.session_id AND s.status = 'done'
LEFT JOIN rounds r ON r.session_id = p.session_id
LEFT JOIN matches m ON m.round_id = r.id
    AND (m.p1 = p.id OR m.p2 = p.id OR m.p3 = p.id OR m.p4 = p.id)
    AND m.score_a IS NOT NULL
WHERE p.user_id = ? AND p.active = 1
`

type GetCareerSummaryRow struct {
	Games      int64
	Wins       int64
	PointShare float64
}

// Cross-mode career summary: games played, wins, and mean per-Match point-share.
// point_share is the average of yourTeamScore / (yourTeamScore + opponentTeamScore)
// over every fully-scored Match in a done Session, each match weighted equally
// regardless of its points target (ADR 0007). Guests fill seats but only the
// user's own player rows are aggregated.
func (q *Queries) GetCareerSummary(ctx context.Context, userID sql.NullString) (GetCareerSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getCareerSummary, userID)
	var i GetCareerSummaryRow
	err := row.Scan(&i.Games, &i.Wins, &i.PointShare)
	return i, err
}

const getMatchResultsSeries = `-- name: GetMatchResultsSeries :many
SELECT
    m.id AS match_id,
    s.game_mode AS mode,
    s.created_at AS date,
    CAST(CASE
        WHEN m.p1 = p.id OR m.p2 = p.id THEN m.score_a
        ELSE m.score_b
    END AS INTEGER) AS points,
    CAST(CASE
        WHEN m.p1 = p.id OR m.p2 = p.id THEN m.score_b
        ELSE m.score_a
    END AS INTEGER) AS conceded
FROM players p
JOIN sessions s ON s.id = p.session_id AND s.status = 'done'
JOIN rounds r ON r.session_id = p.session_id
JOIN matches m ON m.round_id = r.id
    AND (m.p1 = p.id OR m.p2 = p.id OR m.p3 = p.id OR m.p4 = p.id)
    AND m.score_a IS NOT NULL
WHERE p.user_id = ? AND p.active = 1
ORDER BY s.created_at ASC, s.rowid ASC, r.number ASC, m.court ASC
`

type GetMatchResultsSeriesRow struct {
	MatchID  string
	Mode     string
	Date     string
	Points   int64
	Conceded int64
}

// Per-Match results series for the Career Stats page's recent-form curve
// (ADR 0007). One row per fully-scored Match the user played in a done Session,
// oldest-first (by Session date, then round, then court) so the client reads it
// as a time series. INNER JOINs on rounds/matches keep out ended-early Sessions
// with no scored Match. points / conceded are the user's own-team and opponent
// -team score for that Match; the win/draw/loss outcome is derived in Go. date is
// the Session date (Matches carry no timestamp of their own). Guests fill seats
// but only the user's player rows are aggregated.
func (q *Queries) GetMatchResultsSeries(ctx context.Context, userID sql.NullString) ([]GetMatchResultsSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMatchResultsSeries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchResultsSeriesRow{}
	for rows.Next() {
		var i GetMatchResultsSeriesRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Mode,
			&i.Date,
			&i.Points,
			&i.Conceded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModeStats = `-- name: GetModeStats :many
SELECT
    s.game_mode AS mode,
    COUNT(DISTINCT p.session_id) AS tournaments,
    COUNT(m.id) AS games,
    CAST(COALESCE(SUM(
        CASE
            WHEN (m.p1 = p.id OR m.p2 = p.id) AND m.score_a > m.score_b THEN 1
            WHEN (m.p3 = p.id OR m.p4 = p.id) AND m.score_b > m.score_a THEN 1
            ELSE 0
        END
    ), 0) AS INTEGER) AS wins,
    CAST(COALESCE(SUM(
        CASE WHEN m.id IS NOT NULL AND m.score_a = m.score_b THEN 1 ELSE 0 END
    ), 0) AS INTEGER) AS draws,
    CAST(COALESCE(SUM(
        CASE
            WHEN m.p1 = p.id OR m.p2 = p.id THEN m.score_a
            WHEN m.p3 = p.id OR m.p4 = p.id THEN m.score_b
            ELSE 0
        END
    ), 0) AS INTEGER) AS total_points,
    CAST(COALESCE(SUM(
        CASE
            WHEN m.p1 = p.id OR m.p2 = p.id THEN m.score_b
            WHEN m.p3 = p.id OR m.p4 = p.id THEN m.score_a
            ELSE 0
        END
    ), 0) AS INTEGER) AS points_conceded,
    CAST(COALESCE(AVG(
        CASE
            WHEN (m.score_a + m.score_b) = 0 THEN 0.5
            WHEN (m.p1 = p.id OR m.p2 = p.id) THEN CAST(m.score_a AS REAL) / (m.score_a + m.score_b)
            ELSE CAST(m.score_b AS REAL) / (m.score_a + m.score_b)
        END
    ), 0.0) AS REAL) AS point_share
FROM players p
JOIN sessions s ON s.id = p.session_id AND s.status = 'done'
LEFT JOIN rounds r ON r.session_id = p.session_id
LEFT JOIN matches m ON m.round_id = r.id
    AND (m.p1 = p.id OR m.p2 = p.id OR m.p3 = p.id OR m.p4 = p.id)
    AND m.score_a IS NOT NULL
WHERE p.user_id = ? AND p.active = 1
GROUP BY s.game_mode
`

type GetModeStatsRow struct {
	Mode           string
	Tournaments    int64
	Games          int64
	Wins           int64
	Draws          int64
	TotalPoints    int64
	PointsConceded int64
	PointShare     float64
}

// Per-Game-Mode career aggregate for the Career Stats page (ADR 0007). One row
// per Game Mode the user has a done Session in; modes with no history are absent
// and filled in by the store. point_share is the mean per-Match share (same as
// GetCareerSummary) but grouped by mode, since point-share only compares like-for
// -like within one scoring model. total_points / points_conceded are the user's
// own-team and opponent-team score totals across fully-scored matches. tournaments
// counts distinct done Sessions the user joined in that mode. Guests fill seats
// but only the user's own player rows are aggregated.
func (q *Queries) GetModeStats(ctx context.Context, userID sql.NullString) ([]GetModeStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getModeStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModeStatsRow{}
	for rows.Next() {
		var i GetModeStatsRow
		if err := rows.Scan(
			&i.Mode,
			&i.Tournaments,
			&i.Games,
			&i.Wins,
			&i.Draws,
			&i.TotalPoints,
			&i.PointsConceded,
			&i.PointShare,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT user_id, expires_at FROM password_reset_tokens WHERE token_hash = ?
`

type GetPasswordResetTokenRow struct {
	UserID    string
	ExpiresAt string
}

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (GetPasswordResetTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, tokenHash)
	var i GetPasswordResetTokenRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const getTournamentHistorySessions = `-- name: GetTournamentHistorySessions :many
SELECT
    s.id,
    CAST(COALESCE(NULLIF(s.name, ''), 'OpenPadel') AS TEXT) AS name,
    s.status,
    s.created_at,
    COALESCE(s.ended_early, 0) AS ended_early,
    CAST(MAX(CASE WHEN m.score_a IS NOT NULL THEN 1 ELSE 0 END) AS INTEGER) AS scored
FROM players p
JOIN sessions s ON s.id = p.session_id
LEFT JOIN rounds r ON r.session_id = p.session_id
LEFT JOIN matches m ON m.round_id = r.id
    AND (m.p1 = p.id OR m.p2 = p.id OR m.p3 = p.id OR m.p4 = p.id)
WHERE p.user_id = ? AND p.active = 1 AND s.status = 'done'
GROUP BY s.id
ORDER BY s.created_at DESC
`

type GetTournamentHistorySessionsRow struct {
	ID         string
	Name       string
	Status     string
	CreatedAt  string
	EndedEarly int64
	Scored     int64
}

// Done Sessions the user played, newest first, for both the tournament history
// timeline and the cross-mode placement stats (ADR 0007). scored is 1 when the
// user has at least one fully-scored Match in the Session, so placement can
// ignore ended-early Sessions the user never actually finished a game in; the
// finishing rank itself is resolved from the leaderboard in Go.
func (q *Queries) GetTournamentHistorySessions(ctx context.Context, userID sql.NullString) ([]GetTournamentHistorySessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTournamentHistorySessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTournamentHistorySessionsRow{}
	for rows.Next() {
		var i GetTournamentHistorySessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.EndedEarly,
			&i.Scored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingTournaments = `-- name: GetUpcomingTournaments :many
SELECT
    s.id,
    CAST(COALESCE(NULLIF(s.name, ''), 'OpenPadel') AS TEXT) AS name,
    s.status,
    s.game_mode,
    s.courts,
    COUNT(p2.id) AS player_count,
    s.scheduled_at
FROM players p
JOIN sessions s ON s.id = p.session_id
LEFT JOIN players p2 ON p2.session_id = s.id AND p2.active = 1
WHERE p.user_id = ? AND p.active = 1 AND s.status IN ('lobby', 'playing')
GROUP BY s.id
ORDER BY s.status DESC, COALESCE(s.scheduled_at, s.created_at) ASC
`

type GetUpcomingTournamentsRow struct {
	ID          string
	Name        string
	Status      string
	GameMode    string
	Courts      int64
	PlayerCount int64
	ScheduledAt sql.NullString
}

func (q *Queries) GetUpcomingTournaments(ctx context.Context, userID sql.NullString) ([]GetUpcomingTournamentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingTournaments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingTournamentsRow{}
	for rows.Next() {
		var i GetUpcomingTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.GameMode,
			&i.Courts,
			&i.PlayerCount,
			&i.ScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_icon, avatar_color, password_hash, self_rating, created_at
FROM users WHERE email = ?
`

type GetUserByEmailRow struct {
	ID           string
	Email        string
	DisplayName  string
	AvatarIcon   string
	AvatarColor  string
	PasswordHash string
	SelfRating   sql.NullInt64
	CreatedAt    string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarIcon,
		&i.AvatarColor,
		&i.PasswordHash,
		&i.SelfRating,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_icon, avatar_color, password_hash, self_rating, created_at
FROM users WHERE id = ?
`

type GetUserByIDRow struct {
	ID           string
	Email        string
	DisplayName  string
	AvatarIcon   string
	AvatarColor  string
	PasswordHash string
	SelfRating   sql.NullInt64
	CreatedAt    string
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarIcon,
		&i.AvatarColor,
		&i.PasswordHash,
		&i.SelfRating,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIDByToken = `-- name: GetUserIDByToken :one
SELECT user_id FROM auth_tokens WHERE token = ?
`

func (q *Queries) GetUserIDByToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByToken, token)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const incrementTournamentWinCount = `-- name: IncrementTournamentWinCount :exec
UPDATE users SET win_count = win_count + 1 WHERE id = ?
`

func (q *Queries) IncrementTournamentWinCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementTournamentWinCount, id)
	return err
}

const updatePlayerUserIDToNull = `-- name: UpdatePlayerUserIDToNull :exec
UPDATE players SET user_id = NULL WHERE user_id = ?
`

func (q *Queries) UpdatePlayerUserIDToNull(ctx context.Context, userID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updatePlayerUserIDToNull, userID)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE users SET display_name = ?, avatar_icon = ?, avatar_color = ? WHERE id = ?
`

type UpdateProfileParams struct {
	DisplayName string
	AvatarIcon  string
	AvatarColor string
	ID          string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.DisplayName,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.ID,
	)
	return err
}

const updateProfileAvatarOnPlayers = `-- name: UpdateProfileAvatarOnPlayers :exec
UPDATE players SET avatar_icon = ?, avatar_color = ? WHERE user_id = ?
`

type UpdateProfileAvatarOnPlayersParams struct {
	AvatarIcon  string
	AvatarColor string
	UserID      sql.NullString
}

func (q *Queries) UpdateProfileAvatarOnPlayers(ctx context.Context, arg UpdateProfileAvatarOnPlayersParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileAvatarOnPlayers, arg.AvatarIcon, arg.AvatarColor, arg.UserID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserSelfRating = `-- name: UpdateUserSelfRating :exec
UPDATE users SET self_rating = ? WHERE id = ?
`

type UpdateUserSelfRatingParams struct {
	SelfRating sql.NullInt64
	ID         string
}

func (q *Queries) UpdateUserSelfRating(ctx context.Context, arg UpdateUserSelfRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSelfRating, arg.SelfRating, arg.ID)
	return err
}
