// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (token, user_id, created_at) VALUES (?, ?, ?)
`

type CreateAuthTokenParams struct {
	Token     string
	UserID    string
	CreatedAt string
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAuthToken, arg.Token, arg.UserID, arg.CreatedAt)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (token_hash, user_id, expires_at) VALUES (?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	TokenHash string
	UserID    string
	ExpiresAt string
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, display_name, avatar_icon, avatar_color, password_hash, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        string
	DisplayName  string
	AvatarIcon   string
	AvatarColor  string
	PasswordHash string
	CreatedAt    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const deleteAuthToken = `-- name: DeleteAuthToken :exec
DELETE FROM auth_tokens WHERE token = ?
`

func (q *Queries) DeleteAuthToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthToken, token)
	return err
}

const deleteAuthTokensByUserID = `-- name: DeleteAuthTokensByUserID :exec
DELETE FROM auth_tokens WHERE user_id = ?
`

func (q *Queries) DeleteAuthTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthTokensByUserID, userID)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens WHERE token_hash = ?
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetToken, tokenHash)
	return err
}

const deletePasswordResetTokensByUserID = `-- name: DeletePasswordResetTokensByUserID :exec
DELETE FROM password_reset_tokens WHERE user_id = ?
`

func (q *Queries) DeletePasswordResetTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetTokensByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAmericanoCareerStats = `-- name: GetAmericanoCareerStats :one
SELECT
    COUNT(DISTINCT p.session_id) AS tournaments,
    COUNT(m.id) AS games_played,
    CAST(COALESCE(SUM(
        CASE
            WHEN (m.p1 = p.id OR m.p2 = p.id) AND m.score_a > m.score_b THEN 1
            WHEN (m.p3 = p.id OR m.p4 = p.id) AND m.score_b > m.score_a THEN 1
            ELSE 0
        END
    ), 0) AS INTEGER) AS wins,
    CAST(COALESCE(SUM(
        CASE WHEN m.score_a = m.score_b THEN 1 ELSE 0 END
    ), 0) AS INTEGER) AS draws,
    CAST(COALESCE(SUM(
        CASE
            WHEN m.p1 = p.id OR m.p2 = p.id THEN m.score_a
            WHEN m.p3 = p.id OR m.p4 = p.id THEN m.score_b
            ELSE 0
        END
    ), 0) AS INTEGER) AS total_points
FROM players p
JOIN sessions s ON s.id = p.session_id AND s.status = 'done' AND s.game_mode == 'americano'
LEFT JOIN rounds r ON r.session_id = p.session_id
LEFT JOIN matches m ON m.round_id = r.id
    AND (m.p1 = p.id OR m.p2 = p.id OR m.p3 = p.id OR m.p4 = p.id)
    AND m.score_a IS NOT NULL
WHERE p.user_id = ? AND p.active = 1
`

type GetAmericanoCareerStatsRow struct {
	Tournaments int64
	GamesPlayed int64
	Wins        int64
	Draws       int64
	TotalPoints int64
}

func (q *Queries) GetAmericanoCareerStats(ctx context.Context, userID sql.NullString) (GetAmericanoCareerStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAmericanoCareerStats, userID)
	var i GetAmericanoCareerStatsRow
	err := row.Scan(
		&i.Tournaments,
		&i.GamesPlayed,
		&i.Wins,
		&i.Draws,
		&i.TotalPoints,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT user_id, expires_at FROM password_reset_tokens WHERE token_hash = ?
`

type GetPasswordResetTokenRow struct {
	UserID    string
	ExpiresAt string
}

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (GetPasswordResetTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, tokenHash)
	var i GetPasswordResetTokenRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const getTournamentHistorySessions = `-- name: GetTournamentHistorySessions :many
SELECT
    s.id,
    CAST(COALESCE(NULLIF(s.name, ''), 'OpenPadel') AS TEXT) AS name,
    s.status,
    s.created_at,
    COALESCE(s.ended_early, 0) AS ended_early
FROM players p
JOIN sessions s ON s.id = p.session_id
WHERE p.user_id = ? AND p.active = 1 AND s.status = 'done'
GROUP BY s.id
ORDER BY s.created_at DESC
`

type GetTournamentHistorySessionsRow struct {
	ID         string
	Name       string
	Status     string
	CreatedAt  string
	EndedEarly int64
}

func (q *Queries) GetTournamentHistorySessions(ctx context.Context, userID sql.NullString) ([]GetTournamentHistorySessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTournamentHistorySessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTournamentHistorySessionsRow{}
	for rows.Next() {
		var i GetTournamentHistorySessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.EndedEarly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingTournaments = `-- name: GetUpcomingTournaments :many
SELECT
    s.id,
    CAST(COALESCE(NULLIF(s.name, ''), 'OpenPadel') AS TEXT) AS name,
    s.status,
    s.game_mode,
    s.courts,
    COUNT(p2.id) AS player_count,
    s.scheduled_at
FROM players p
JOIN sessions s ON s.id = p.session_id
LEFT JOIN players p2 ON p2.session_id = s.id AND p2.active = 1
WHERE p.user_id = ? AND p.active = 1 AND s.status IN ('lobby', 'playing')
GROUP BY s.id
ORDER BY s.status DESC, COALESCE(s.scheduled_at, s.created_at) ASC
`

type GetUpcomingTournamentsRow struct {
	ID          string
	Name        string
	Status      string
	GameMode    string
	Courts      int64
	PlayerCount int64
	ScheduledAt sql.NullString
}

func (q *Queries) GetUpcomingTournaments(ctx context.Context, userID sql.NullString) ([]GetUpcomingTournamentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingTournaments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingTournamentsRow{}
	for rows.Next() {
		var i GetUpcomingTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.GameMode,
			&i.Courts,
			&i.PlayerCount,
			&i.ScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_icon, avatar_color, password_hash, created_at
FROM users WHERE email = ?
`

type GetUserByEmailRow struct {
	ID           string
	Email        string
	DisplayName  string
	AvatarIcon   string
	AvatarColor  string
	PasswordHash string
	CreatedAt    string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarIcon,
		&i.AvatarColor,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_icon, avatar_color, password_hash, created_at
FROM users WHERE id = ?
`

type GetUserByIDRow struct {
	ID           string
	Email        string
	DisplayName  string
	AvatarIcon   string
	AvatarColor  string
	PasswordHash string
	CreatedAt    string
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarIcon,
		&i.AvatarColor,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIDByToken = `-- name: GetUserIDByToken :one
SELECT user_id FROM auth_tokens WHERE token = ?
`

func (q *Queries) GetUserIDByToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByToken, token)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const incrementTournamentWinCount = `-- name: IncrementTournamentWinCount :exec
UPDATE users SET win_count = win_count + 1 WHERE id = ?
`

func (q *Queries) IncrementTournamentWinCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementTournamentWinCount, id)
	return err
}

const updatePlayerUserIDToNull = `-- name: UpdatePlayerUserIDToNull :exec
UPDATE players SET user_id = NULL WHERE user_id = ?
`

func (q *Queries) UpdatePlayerUserIDToNull(ctx context.Context, userID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updatePlayerUserIDToNull, userID)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE users SET display_name = ?, avatar_icon = ?, avatar_color = ? WHERE id = ?
`

type UpdateProfileParams struct {
	DisplayName string
	AvatarIcon  string
	AvatarColor string
	ID          string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.DisplayName,
		arg.AvatarIcon,
		arg.AvatarColor,
		arg.ID,
	)
	return err
}

const updateProfileAvatarOnPlayers = `-- name: UpdateProfileAvatarOnPlayers :exec
UPDATE players SET avatar_icon = ?, avatar_color = ? WHERE user_id = ?
`

type UpdateProfileAvatarOnPlayersParams struct {
	AvatarIcon  string
	AvatarColor string
	UserID      sql.NullString
}

func (q *Queries) UpdateProfileAvatarOnPlayers(ctx context.Context, arg UpdateProfileAvatarOnPlayersParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileAvatarOnPlayers, arg.AvatarIcon, arg.AvatarColor, arg.UserID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
